sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu16.04  -t monit_xenial   .
    - docker build  -f test/Dockerfile-ubuntu14.04  -t monit_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t monit_precise  .
    - docker build  -f test/Dockerfile-debian8      -t monit_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t monit_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t monit_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t monit_centos6  .

script:
    - docker run  -v $(pwd):/data  monit_xenial
    - docker run  -v $(pwd):/data  monit_trusty
    - docker run  -v $(pwd):/data  monit_precise
    - docker run  -v $(pwd):/data  monit_jessie
    - docker run  -v $(pwd):/data  monit_wheezy
    - docker run  -v $(pwd):/data  monit_centos7
    - docker run  -v $(pwd):/data  monit_centos6

    - echo "==> Validating the test results..."
    - grep 'Monit .*uptime:' result-ubuntu16.04
    - grep 'Monit .*uptime:' result-ubuntu14.04
    - grep 'Monit .*uptime:' result-ubuntu12.04
    - grep 'Monit .*uptime:' result-debian8
    - grep 'Monit .*uptime:' result-debian7
    - grep 'Monit .*uptime:' result-centos7
    - grep 'Monit .*uptime:' result-centos6

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
