sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t monit_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t monit_precise  .
    - docker build  -f test/Dockerfile-debian8      -t monit_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t monit_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t monit_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t monit_centos6  .

script:
    - docker run -d -v $(pwd):/data --name c1 monit_trusty
    - docker run -d -v $(pwd):/data --name c2 monit_precise
    - docker run -d -v $(pwd):/data --name c3 monit_jessie
    - docker run -d -v $(pwd):/data --name c4 monit_wheezy
    - docker run -d -v $(pwd):/data --name c5 monit_centos7
    - docker run -d -v $(pwd):/data --name c6 monit_centos6
    - sleep 30

    - echo "==> Validating the test results..."
    - grep '^The Monit daemon.*uptime' result-ubuntu14.04
    - grep '^The Monit daemon.*uptime' result-ubuntu12.04
    - grep '^The Monit daemon.*uptime' result-debian8
    - grep '^The Monit daemon.*uptime' result-debian7
    - grep '^The Monit daemon.*uptime' result-centos7
    - grep '^The Monit daemon.*uptime' result-centos6
