---
# file: tasks/install.yml
#
# Install monit from source code.
#
# @see https://mmonit.com/wiki/Monit/Installation
#


- name: set internal variables for convenience
  set_fact:
    monit_tarball_file: "monit-{{ monit_version }}-linux-x64.tar.gz"
  when: ansible_userspace_bits == "64"

- name: set internal variables for convenience
  set_fact:
    monit_tarball_file: "monit-{{ monit_version }}-linux-x86.tar.gz"
  when: ansible_userspace_bits == "32"



- name: download tarball via Ansible's get_url
  get_url: url="https://mmonit.com/monit/dist/binary/{{ monit_version }}/{{ monit_tarball_file }}"  dest="{{ monit_download_path }}/"
  ignore_errors: yes
  register: monit_tarball_downloaded

- name: install curl
  yum: name=curl state=present
  when: (monit_tarball_downloaded.failed | default(false))  and  ansible_pkg_mgr == "yum"

- name: install curl
  apt: name=curl state=present
  when: (monit_tarball_downloaded.failed | default(false))  and  ansible_pkg_mgr == "apt"

- name: download tarball via curl
  command: curl -sSL -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36" -o "{{ monit_download_path }}/{{ monit_tarball_file }}" "https://mmonit.com/monit/dist/binary/{{ monit_version }}/{{ monit_tarball_file }}"
  when: (monit_tarball_downloaded.failed | default(false))



- name: uutar tarball
  unarchive:
    src: "{{ monit_download_path }}/{{ monit_tarball_file }}"
    dest: "{{ monit_download_path }}"
    copy: no

- name: install executable
  command: cp  "{{ monit_download_path }}/monit-{{ monit_version }}/bin/monit"  "{{ monit_install_path }}/monit"



- name: clean tarball, if necessary
  file: path={{ item }}  state=absent
  with_items:
    - "{{ monit_download_path }}/{{ monit_tarball_file }}"
    - "{{ monit_download_path }}/monit-{{ monit_version }}"
  when: monit_clean_tarball



- name: copy INIT script to server
  template: src="../templates/monit.sysvinit.debian.sh.j2"  dest="/etc/init.d/monit"  mode="a+x"
  when: ansible_os_family == "Debian"

- name: copy INIT script to server
  template: src="../templates/monit.sysvinit.redhat.sh.j2"  dest="/etc/init.d/monit"  mode="a+x"
  when: ansible_os_family == "RedHat"

- name: set INIT status
  service: name=monit enabled=yes

- name: set monit variable for Debian/Ubuntu
  copy: src="../files/etc-default-monit"  dest=/etc/default/monit
  when: ansible_os_family == "Debian"
