---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set monit_use_service = True, if not defined
  set_fact:
    monit_use_service: True
  when: monit_use_service is not defined
